### ISSUE TITLE
User can add/edit subjects

### ISSUE THREAD

**Issue by cmatheny** [1701-jan09-java/interview-evaluations#40]
Add crud enpoints for subject table

**Comment by tjkemper** [comment]
@cmatheny are you taking this?

**Comment by cmatheny** [comment]
I can, it shouldn't take long. Want it before or after the sql script?

**Comment by tjkemper** [comment]
Issue #39 probably takes priority. I'll leave this issue unassigned for now.

**Comment by eeolivas** [comment]
i got it

**Comment by eeolivas** [comment]
#48 fixed this issue
