### ISSUE TITLE
Explain Makefile

### ISSUE THREAD

**Issue by tjkemper** [1701-jan09-java/interview-evaluations#56]
Write [Makefile wiki](https://github.com/1701-jan09-java/interview-evaluations/wiki/Makefile) to explain how to use our `Makefile`

**Comment by cmatheny** [comment]
@tjkemper 
https://github.com/1701-jan09-java/interview-evaluations/wiki/Makefile

This is complete if it looks good to you.

**Comment by tjkemper** [comment]
lgtm
